"""Executive PDF report generation."""

from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def _draw_navbar(c: canvas.Canvas, width: float, height: float, page_title: str) -> None:
    c.setFillColorRGB(0.039, 0.047, 0.09)
    c.rect(0, height - 70, width, 70, fill=1, stroke=0)
    c.setFillColorRGB(0.39, 0.40, 0.95)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(36, height - 42, "ResumeIQ")
    c.setFillColorRGB(0.97, 0.98, 1.0)
    c.setFont("Helvetica-Bold", 11)
    c.drawRightString(width - 36, height - 36, page_title)
    c.setFillColorRGB(0.55, 0.58, 0.7)
    c.setFont("Helvetica", 9)
    c.drawString(36, height - 58, "Resume Intelligence Platform")
    c.setFillColorRGB(0.039, 0.047, 0.09)
    c.rect(0, 0, width, 44, fill=1, stroke=0)
    c.setFillColorRGB(0.45, 0.47, 0.55)
    c.setFont("Helvetica", 8)
    c.drawString(36, 16, "Generated by ResumeIQ  |  Confidential")
    c.drawRightString(width - 36, 16, datetime.now().strftime("%B %d, %Y"))


def _score_color(score: int) -> tuple[float, float, float]:
    if score >= 80:
        return (0.063, 0.725, 0.506)
    if score >= 60:
        return (0.961, 0.620, 0.043)
    return (0.937, 0.267, 0.267)


def _draw_progress_bar(
    c: canvas.Canvas, x: float, y: float, width: float,
    score: int, label: str, weight: str = "",
) -> None:
    color = _score_color(score)
    c.setFillColorRGB(0.55, 0.58, 0.7)
    c.setFont("Helvetica", 9)
    c.drawString(x, y + 2, label)
    c.drawRightString(x + width, y + 2, f"{weight}  {score}%" if weight else f"{score}%")
    y -= 12
    c.setFillColorRGB(0.12, 0.14, 0.22)
    c.roundRect(x, y, width, 7, 3, fill=1, stroke=0)
    c.setFillColorRGB(*color)
    c.roundRect(x, y, max((score / 100) * width, 4), 7, 3, fill=1, stroke=0)


def generate_pdf(data: dict, pdf_path: str) -> None:
    """Generate a 3-page executive PDF report."""
    c = canvas.Canvas(pdf_path, pagesize=A4)
    width, height = A4
    margin = 36
    content_w = width - 2 * margin

    role = data["role"]
    filename = data["filename"]
    ats_score = data["ats_score"]

    c.setFillColorRGB(0.039, 0.047, 0.09)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    _draw_navbar(c, width, height, "Executive Report")
    cx, cy = width / 2, height / 2 + 40
    score_col = _score_color(ats_score)
    c.setStrokeColorRGB(0.12, 0.14, 0.22)
    c.setLineWidth(14)
    c.circle(cx, cy, 68, fill=0, stroke=1)
    c.setFillColorRGB(*score_col)
    c.setFont("Helvetica-Bold", 44)
    c.drawCentredString(cx, cy - 16, str(ats_score))
    c.setFont("Helvetica", 13)
    c.setFillColorRGB(0.55, 0.58, 0.7)
    c.drawCentredString(cx, cy - 34, "/ 100  ATS Score")
    c.setFillColorRGB(0.97, 0.98, 1.0)
    c.setFont("Helvetica-Bold", 24)
    c.drawCentredString(cx, cy + 110, "Resume Analysis Report")
    c.setFillColorRGB(0.55, 0.58, 0.7)
    c.setFont("Helvetica", 13)
    c.drawCentredString(cx, cy + 88, f"Role Target: {role}")
    c.setFont("Helvetica", 10)
    c.drawCentredString(cx, cy + 70, f"File: {filename}")
    rec_label = (
        "HIGHLY RECOMMENDED" if ats_score >= 80
        else "CONSIDER WITH REVISIONS" if ats_score >= 60
        else "NEEDS IMPROVEMENT"
    )
    c.setFillColorRGB(*score_col)
    c.setFont("Helvetica-Bold", 11)
    c.drawCentredString(cx, cy - 88, rec_label)
    bar_x = (width - 320) / 2
    bar_y = cy - 120
    bar_w = 320
    c.setFillColorRGB(0.97, 0.98, 1.0)
    c.setFont("Helvetica-Bold", 10)
    c.drawCentredString(cx, bar_y + 10, "SCORE BREAKDOWN")
    bar_y -= 14
    for label, score, weight in [
        ("Keyword Match", data["keyword_score"], "40%"),
        ("Projects", data["project_score"], "20%"),
        ("Experience", data["experience_score"], "20%"),
        ("Education", data["education_score"], "10%"),
        ("Formatting", data["formatting_score"], "10%"),
    ]:
        _draw_progress_bar(c, bar_x, bar_y, bar_w, score, label, weight)
        bar_y -= 28
    c.showPage()

    c.setFillColorRGB(0.039, 0.047, 0.09)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    _draw_navbar(c, width, height, "Skills Analysis")
    y = height - 96
    c.setFillColorRGB(0.97, 0.98, 1.0)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, y, "Skills Analysis")
    y -= 8
    c.setStrokeColorRGB(0.15, 0.17, 0.28)
    c.setLineWidth(0.8)
    c.line(margin, y, width - margin, y)
    y -= 20
    c.setFillColorRGB(0.063, 0.725, 0.506)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "[+] MATCHED SKILLS (with evidence)")
    y -= 16
    evidence_list: list[dict] = data.get("skill_evidence", [])
    if evidence_list:
        c.setFont("Helvetica", 9)
        for ev in evidence_list:
            if y < 60:
                break
            strength_label = {"strong": "[STRONG]", "moderate": "[MOD]", "weak": "[WEAK]"}.get(
                ev.get("strength", ""), ""
            )
            c.setFillColorRGB(0.063, 0.725, 0.506 if ev.get("strength") == "strong" else 0.4)
            c.drawString(margin + 6, y, f"{ev['skill'].title()}  {strength_label}")
            c.setFillColorRGB(0.55, 0.58, 0.7)
            evidence_text = ev.get("evidence", "")[:90]
            c.drawString(margin + 120, y, f'"{evidence_text}"')
            y -= 14
    else:
        for skill in data.get("skills_found", []):
            if y < 60:
                break
            c.setFillColorRGB(0.063, 0.725, 0.506)
            c.circle(margin + 6, y + 3, 2.5, fill=1, stroke=0)
            c.setFillColorRGB(0.65, 0.68, 0.78)
            c.drawString(margin + 15, y, skill.title())
            y -= 15
    y -= 16
    c.setFillColorRGB(0.937, 0.267, 0.267)
    c.setFont("Helvetica-Bold", 11)
    c.drawString(margin, y, "[-] MISSING SKILLS")
    y -= 16
    c.setFont("Helvetica", 10)
    for skill in data.get("missing_skills", []):
        if y < 60:
            break
        c.setFillColorRGB(0.961, 0.620, 0.043)
        c.circle(margin + 6, y + 3, 2.5, fill=1, stroke=0)
        c.setFillColorRGB(0.65, 0.68, 0.78)
        c.drawString(margin + 15, y, skill.title())
        y -= 15
    c.showPage()

    c.setFillColorRGB(0.039, 0.047, 0.09)
    c.rect(0, 0, width, height, fill=1, stroke=0)
    _draw_navbar(c, width, height, "Improvement Roadmap")
    y = height - 96
    c.setFillColorRGB(0.97, 0.98, 1.0)
    c.setFont("Helvetica-Bold", 15)
    c.drawString(margin, y, "Improvement Roadmap")
    y -= 8
    c.setStrokeColorRGB(0.15, 0.17, 0.28)
    c.setLineWidth(0.8)
    c.line(margin, y, width - margin, y)
    y -= 20

    def _section(heading: str, color: tuple, items: list[str], prefix: str = "") -> None:
        nonlocal y
        if not items:
            return
        c.setFillColorRGB(*color)
        c.setFont("Helvetica-Bold", 11)
        c.drawString(margin, y, heading)
        y -= 16
        c.setFont("Helvetica", 10)
        for item in items:
            if y < 60:
                return
            c.setFillColorRGB(*color)
            c.drawString(margin + 6, y, prefix or "-")
            c.setFillColorRGB(0.65, 0.68, 0.78)
            c.drawString(margin + 20, y, (item[:90] + "…") if len(item) > 90 else item)
            y -= 15
        y -= 10

    _section("STRENGTHS", (0.063, 0.725, 0.506), data.get("strengths", []), "^")
    _section("AREAS TO IMPROVE", (0.961, 0.620, 0.043), data.get("weaknesses", []), "!")
    _section(
        "RECRUITER HONEST FEEDBACK",
        (0.937, 0.267, 0.267),
        data.get("recruiter_feedback", [])[:4],
        "!",
    )
    _section("RECOMMENDATIONS", (0.39, 0.40, 0.95), data.get("recommendations", []), ">")

    summary = data.get("recruiter_summary", "")
    if summary and y > 90:
        y -= 10
        box_h = 44
        c.setFillColorRGB(0.07, 0.09, 0.18)
        c.roundRect(margin, y - box_h, content_w, box_h, 6, fill=1, stroke=0)
        c.setFillColorRGB(0.55, 0.58, 0.7)
        c.setFont("Helvetica-Bold", 8)
        c.drawString(margin + 10, y - 14, "RECRUITER SUMMARY")
        c.setFont("Helvetica", 9)
        c.setFillColorRGB(0.65, 0.68, 0.78)
        c.drawString(margin + 10, y - 30, (summary[:105] + "…") if len(summary) > 105 else summary)

    c.save()
